### ISSUE TITLE
One click deploy

### ISSUE THREAD

**Issue by syvlabs** [thinkingmachines/bqup#28]
What's the best way to set up a one-click deploy thing?

**Comment by syk0saje** [comment]
Depends what you mean by "best" and what your requirements are for deployment. If fastest barebones deployment, I'm guessing a shell script would be easiest.

Things that can be automated:
* gce instantiation
* bqup installation
* cron setup
* creating instance repo
* setting origin url
* fetching public key

Not sure if can automate:
* creating github repo
* adding deploy key

**Comment by syk0saje** [comment]
migrated: https://github.com/thinkingmachines/bqup-starter/issues/3
